### ISSUE TITLE
The common.sccs file is being replicated many times in final bundle

### ISSUE THREAD

**Issue by carlosesilva** [bu-ist/bu-learning-blocks#46]
The common.sccs file is being replicated many times in the final bundle. 

I noticed this after ejecting from create-guten-block but I think this was maybe happening before as well. If this was indeed happening before ejecting, we should probably open an issue upstream as well.

**Comment by carlosesilva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Common.scss being included multiple times](https://trello.com/c/Ko2JPqVW/41-commonscss-being-included-multiple-times)

**Comment by jdub233** [comment]
Confirmed, I'm seeing this as well.
