### ISSUE TITLE
Blocks throw "Undefined index: type" PHP Notice

### ISSUE THREAD

**Issue by DannyCrews** [bu-ist/bu-learning-blocks#76]
Query Monitor shows PHP notices when rendering blocks on the front end:

Undefined index: fontSize
Undefined index: textColorControl
Undefined index: backgroundColorControl
Undefined index: type

**Comment by jdub233** [comment]
I'm looking into this, I think this issue may describe the situation:

https://github.com/WordPress/gutenberg/issues/8522

**Comment by jdub233** [comment]
Also the first user contributed note on the `register_block_type` docs touches on type declarations on attributes:

https://developer.wordpress.org/reference/functions/register_block_type/#user-contributed-notes
